name: Decompress LZ10 file

on:
  push:
    paths:
      - '**.lz10'
      - '**.lz7'

jobs:
  decompress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run LZ10 decompressor
        run: |
          python3 lz10_extractor.py *.lz10 || true
          python3 lz10_extractor.py *.lz7 || true

      - name: Upload decompressed files
        uses: actions/upload-artifact@v4
        with:
          name: decompressed-output
          path: |
            *.decompressed
