name: Decompress LZ10 File

on:
  workflow_dispatch:  # manual trigger

jobs:
  decompress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build decompressor
        run: go build -o lz10decompress main.go

      - name: Decompress file
        run: ./lz10decompress input.lz7 output.bin

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: decompressed-output
          path: output.bin
