name: Decompress LZ7 File (Python)

on:
  workflow_dispatch:  # allows manual triggering in GitHub Actions

jobs:
  decompress:
    name: Run Python LZ7 Decompressor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run LZ7 Decompressor
        run: |
          # Replace these names if yours differ
          python LZ77Extractor.py wwwlib-rvl.lz7 wwwlib-rvl.arc

      - name: Upload Decompressed File
        uses: actions/upload-artifact@v4
        with:
          name: decompressed-arc
          path: wwwlib-rvl.arc
