name: Decompress LZ7/LZ10 and Extract ARC

on:
  workflow_dispatch: # manual trigger

jobs:
  decompress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirements
        run: |
          pip install --upgrade pip

      - name: Decompress LZ10/LZ7
        run: |
          python lz10_extractor.py "wwwlib-rvl.lz7"  # produces wwwlib-rvl.arc

      - name: Extract ARC
        run: |
          python extract_arc.py "wwwlib-rvl.arc"

      - name: Upload extracted files
        uses: actions/upload-artifact@v4
        with:
          name: extracted-files
          path: output/
