name: Decompress LZ10 File

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Name of the LZ10 file in the repo'
        required: true
        default: 'wwwlib-rvl.lz7'

jobs:
  decompress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: List files for debugging
        run: ls -R

      - name: Run LZ10 extractor
        run: |
          python lz10_extractor.py "${{ github.event.inputs.file }}"

      - name: Show resulting files
        run: ls -lh
