name: Decompress LZ7 File

on:
  workflow_dispatch:  # allows manual runs from the Actions tab

jobs:
  decompress:
    name: Run LZ7 Decompressor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build LZ7 Decompressor
        run: |
          go build -o lz7extract main.go

      - name: Run Decompressor
        run: |
          # Change filenames here if needed
          ./lz7extract wwwlib-rvl.lz7 wwwlib-rvl.arc

      - name: Upload Output File
        uses: actions/upload-artifact@v4
        with:
          name: decompressed-arc
          path: wwwlib-rvl.arc
